"""adding AVU custom tables and foreign key for who tables

Revision ID: 460d623af7cb
Revises: 
Create Date: 2021-11-17 14:42:11.994401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '460d623af7cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sample_id', 'hcv_glue_avu_sequence', ['sample_id'], unique=False)
    op.create_index('who_country_id', 'hcv_glue_avu_sequence', ['who_country_id'], unique=False)
    op.create_foreign_key(None, 'hcv_glue_avu_sequence', 'hcv_glue_avu_sample', ['sample_id'], ['id'])
    op.create_foreign_key(None, 'hcv_glue_avu_sequence', 'hcv_glue_avu_who_country', ['who_country_id'], ['id'])
    op.create_foreign_key(None, 'hcv_glue_avu_who_country', 'hcv_glue_avu_who_sub_region', ['who_sub_region_id'], ['id'])
    op.create_foreign_key(None, 'hcv_glue_avu_who_country', 'hcv_glue_avu_who_region', ['who_region_id'], ['id'])
    op.create_foreign_key(None, 'hcv_glue_avu_who_country', 'hcv_glue_avu_who_intermediate_region', ['who_intermediate_region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hcv_glue_avu_who_country', type_='foreignkey')
    op.drop_constraint(None, 'hcv_glue_avu_who_country', type_='foreignkey')
    op.drop_constraint(None, 'hcv_glue_avu_who_country', type_='foreignkey')
    op.drop_constraint(None, 'hcv_glue_avu_sequence', type_='foreignkey')
    op.drop_constraint(None, 'hcv_glue_avu_sequence', type_='foreignkey')
    op.drop_index('who_country_id', table_name='hcv_glue_avu_sequence')
    op.drop_index('sample_id', table_name='hcv_glue_avu_sequence')
    op.create_table('default_sequence',
    sa.Column('format', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sequence_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_name'], ['default_source.name'], name='default_sequence_ibfk_1'),
    sa.PrimaryKeyConstraint('sequence_id', 'source_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_seq_orig_data',
    sa.Column('packed_data', mysql.LONGBLOB(), nullable=False),
    sa.Column('sequence_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_name', 'sequence_id'], ['default_sequence.source_name', 'default_sequence.sequence_id'], name='default_seq_orig_data_ibfk_1'),
    sa.PrimaryKeyConstraint('sequence_id', 'source_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_alignment_member',
    sa.Column('alignment_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('reference_member', mysql.BIT(length=1), nullable=False),
    sa.Column('sequence_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['alignment_name'], ['default_alignment.name'], name='default_alignment_member_ibfk_1'),
    sa.ForeignKeyConstraint(['source_name', 'sequence_id'], ['default_sequence.source_name', 'default_sequence.sequence_id'], name='default_alignment_member_ibfk_2'),
    sa.PrimaryKeyConstraint('alignment_name', 'sequence_id', 'source_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('custom_table',
    sa.Column('id_field_length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], name='custom_table_ibfk_1'),
    sa.PrimaryKeyConstraint('name', 'project_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_source',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_feature_segment',
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('splice_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('transcription_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('translation_modifier_name', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ref_seq_name', 'feature_name'], ['default_feature_location.ref_seq_name', 'default_feature_location.feature_name'], name='default_feature_segment_ibfk_1'),
    sa.PrimaryKeyConstraint('feature_name', 'ref_end', 'ref_seq_name', 'ref_start'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_feature',
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('parent_name', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_name'], ['default_feature.name'], name='default_feature_ibfk_1'),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_aligned_segment',
    sa.Column('alignment_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('member_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('member_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ref_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ref_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sequence_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_name', 'sequence_id', 'alignment_name'], ['default_alignment_member.source_name', 'default_alignment_member.sequence_id', 'default_alignment_member.alignment_name'], name='default_aligned_segment_ibfk_1'),
    sa.PrimaryKeyConstraint('alignment_name', 'member_end', 'member_start', 'ref_end', 'ref_start', 'sequence_id', 'source_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_module_resource',
    sa.Column('content', mysql.LONGBLOB(), nullable=True),
    sa.Column('module_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['module_name'], ['default_module.name'], name='default_module_resource_ibfk_1'),
    sa.PrimaryKeyConstraint('module_name', 'name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_alignment',
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('parent_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_name'], ['default_alignment.name'], name='default_alignment_ibfk_1'),
    sa.ForeignKeyConstraint(['ref_seq_name'], ['default_reference_sequence.name'], name='default_alignment_ibfk_2'),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('link',
    sa.Column('dest_link_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dest_table_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('multiplicity', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('src_link_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('src_table_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], name='link_ibfk_1'),
    sa.PrimaryKeyConstraint('project_name', 'src_link_name', 'src_table_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('project',
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_var_almt_note',
    sa.Column('alignment_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('variation_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['alignment_name'], ['default_alignment.name'], name='default_var_almt_note_ibfk_1'),
    sa.ForeignKeyConstraint(['ref_seq_name', 'feature_name', 'variation_name'], ['default_variation.ref_seq_name', 'default_variation.feature_name', 'default_variation.name'], name='default_var_almt_note_ibfk_2'),
    sa.PrimaryKeyConstraint('alignment_name', 'feature_name', 'ref_seq_name', 'variation_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_feature_location',
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['feature_name'], ['default_feature.name'], name='default_feature_location_ibfk_1'),
    sa.ForeignKeyConstraint(['ref_seq_name'], ['default_reference_sequence.name'], name='default_feature_location_ibfk_2'),
    sa.PrimaryKeyConstraint('feature_name', 'ref_seq_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_variation_metatag',
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('metatag_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('metatag_value', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('variation_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('feature_name', 'metatag_name', 'ref_seq_name', 'variation_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_feature_metatag',
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['feature_name'], ['default_feature.name'], name='default_feature_metatag_ibfk_1'),
    sa.PrimaryKeyConstraint('feature_name', 'name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('AUTO_PK_SUPPORT',
    sa.Column('TABLE_NAME', mysql.CHAR(length=100), nullable=False),
    sa.Column('NEXT_ID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('TABLE_NAME', 'AUTO_PK_SUPPORT', ['TABLE_NAME'], unique=False)
    op.create_table('default_member_floc_note',
    sa.Column('alignment_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sequence_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ref_seq_name', 'feature_name'], ['default_feature_location.ref_seq_name', 'default_feature_location.feature_name'], name='default_member_floc_note_ibfk_1'),
    sa.PrimaryKeyConstraint('alignment_name', 'feature_name', 'ref_seq_name', 'sequence_id', 'source_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('schema_version',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('schema_version', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_module',
    sa.Column('config', mysql.LONGBLOB(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('field',
    sa.Column('max_length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], name='field_ibfk_1'),
    sa.PrimaryKeyConstraint('name', 'project_name', 'table_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_variation',
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('feature_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ref_seq_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ref_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ref_seq_name', 'feature_name'], ['default_feature_location.ref_seq_name', 'default_feature_location.feature_name'], name='default_variation_ibfk_1'),
    sa.PrimaryKeyConstraint('feature_name', 'name', 'ref_seq_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('default_reference_sequence',
    sa.Column('creation_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sequence_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_name', 'sequence_id'], ['default_sequence.source_name', 'default_sequence.sequence_id'], name='default_reference_sequence_ibfk_1'),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
