-- MySQL Script generated by MySQL Workbench
-- Fri 05 Nov 2021 15:31:04 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema GLUE_TOOLS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GLUE_TOOLS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GLUE_TOOLS` DEFAULT CHARACTER SET utf8 ;
USE `GLUE_TOOLS` ;

-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_source` (
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_sequence` (
  `format` VARCHAR(50) NOT NULL,
  `sequence_id` VARCHAR(50) NOT NULL,
  `source_name` VARCHAR(50) NOT NULL,
  `gb_gi_number` VARCHAR(50) NULL DEFAULT NULL,
  `gb_primary_accession` VARCHAR(50) NULL DEFAULT NULL,
  `gb_accession_version` VARCHAR(50) NULL DEFAULT NULL,
  `gb_locus` VARCHAR(50) NULL DEFAULT NULL,
  `gb_length` INT(11) NULL DEFAULT NULL,
  `gb_recombinant` BIT(1) NULL DEFAULT NULL,
  `gb_organism` VARCHAR(50) NULL DEFAULT NULL,
  `gb_isolate` VARCHAR(300) NULL DEFAULT NULL,
  `gb_taxonomy` VARCHAR(200) NULL DEFAULT NULL,
  `gb_host` VARCHAR(50) NULL DEFAULT NULL,
  `gb_pubmed_id` VARCHAR(50) NULL DEFAULT NULL,
  `gb_country` VARCHAR(50) NULL DEFAULT NULL,
  `gb_place_sampled` VARCHAR(200) NULL DEFAULT NULL,
  `gb_collection_year` INT(11) NULL DEFAULT NULL,
  `gb_collection_month` VARCHAR(50) NULL DEFAULT NULL,
  `gb_collection_month_day` INT(11) NULL DEFAULT NULL,
  `gb_create_date` DATE NULL DEFAULT NULL,
  `gb_update_date` DATE NULL DEFAULT NULL,
  `gb_genotype` VARCHAR(50) NULL DEFAULT NULL,
  `gb_subtype` VARCHAR(50) NULL DEFAULT NULL,
  `earliest_collection_year` INT(11) NULL DEFAULT NULL,
  `latest_collection_year` INT(11) NULL DEFAULT NULL,
  `genotype` VARCHAR(50) NULL DEFAULT NULL,
  `subtype` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_method` VARCHAR(200) NULL DEFAULT NULL,
  `reference_status` VARCHAR(20) NULL DEFAULT NULL,
  `gb_lab_construct` BIT(1) NULL DEFAULT NULL,
  `hcv_wg_pipeline` VARCHAR(100) NULL DEFAULT NULL,
  `pipeline_version` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_polyprotein` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_core` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_e1` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_e2` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_p7` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_ns2` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_ns3` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_ns4a` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_ns4b` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_ns5a` VARCHAR(50) NULL DEFAULT NULL,
  `genotyping_ns5b` VARCHAR(50) NULL DEFAULT NULL,
  `who_country_id` VARCHAR(50) NULL DEFAULT NULL,
  `sample_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`sequence_id`, `source_name`),
  INDEX `source_name` (`source_name` ASC),
  CONSTRAINT `hcv_glue_avu_sequence_ibfk_1`
    FOREIGN KEY (`source_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_source` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_reference_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_reference_sequence` (
  `creation_time` BIGINT(20) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `sequence_id` VARCHAR(50) NOT NULL,
  `source_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `source_name` (`source_name` ASC, `sequence_id` ASC),
  CONSTRAINT `hcv_glue_avu_reference_sequence_ibfk_1`
    FOREIGN KEY (`source_name` , `sequence_id`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_sequence` (`source_name` , `sequence_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_alignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_alignment` (
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `parent_name` VARCHAR(50) NULL DEFAULT NULL,
  `ref_seq_name` VARCHAR(50) NULL DEFAULT NULL,
  `phylogeny` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `parent_name` (`parent_name` ASC),
  INDEX `ref_seq_name` (`ref_seq_name` ASC),
  CONSTRAINT `hcv_glue_avu_alignment_ibfk_1`
    FOREIGN KEY (`parent_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_alignment` (`name`),
  CONSTRAINT `hcv_glue_avu_alignment_ibfk_2`
    FOREIGN KEY (`ref_seq_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_reference_sequence` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_alignment_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_alignment_member` (
  `alignment_name` VARCHAR(50) NOT NULL,
  `reference_member` BIT(1) NOT NULL,
  `sequence_id` VARCHAR(50) NOT NULL,
  `source_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`alignment_name`, `sequence_id`, `source_name`),
  INDEX `source_name` (`source_name` ASC, `sequence_id` ASC),
  CONSTRAINT `hcv_glue_avu_alignment_member_ibfk_1`
    FOREIGN KEY (`alignment_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_alignment` (`name`),
  CONSTRAINT `hcv_glue_avu_alignment_member_ibfk_2`
    FOREIGN KEY (`source_name` , `sequence_id`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_sequence` (`source_name` , `sequence_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_aligned_segment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_aligned_segment` (
  `alignment_name` VARCHAR(50) NOT NULL,
  `member_end` INT(11) NOT NULL,
  `member_start` INT(11) NOT NULL,
  `ref_end` INT(11) NOT NULL,
  `ref_start` INT(11) NOT NULL,
  `sequence_id` VARCHAR(50) NOT NULL,
  `source_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`alignment_name`, `member_end`, `member_start`, `ref_end`, `ref_start`, `sequence_id`, `source_name`),
  INDEX `source_name` (`source_name` ASC, `sequence_id` ASC, `alignment_name` ASC),
  CONSTRAINT `hcv_glue_avu_aligned_segment_ibfk_1`
    FOREIGN KEY (`source_name` , `sequence_id` , `alignment_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_alignment_member` (`source_name` , `sequence_id` , `alignment_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_drug` (
  `id` VARCHAR(50) NOT NULL,
  `manufacturer` VARCHAR(50) NULL DEFAULT NULL,
  `therapy_class` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_feature` (
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `parent_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `parent_name` (`parent_name` ASC),
  CONSTRAINT `hcv_glue_avu_feature_ibfk_1`
    FOREIGN KEY (`parent_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_feature` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_feature_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_feature_location` (
  `feature_name` VARCHAR(50) NOT NULL,
  `ref_seq_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`feature_name`, `ref_seq_name`),
  INDEX `ref_seq_name` (`ref_seq_name` ASC),
  CONSTRAINT `hcv_glue_avu_feature_location_ibfk_1`
    FOREIGN KEY (`feature_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_feature` (`name`),
  CONSTRAINT `hcv_glue_avu_feature_location_ibfk_2`
    FOREIGN KEY (`ref_seq_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_reference_sequence` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_feature_metatag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_feature_metatag` (
  `feature_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `value` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`feature_name`, `name`),
  CONSTRAINT `hcv_glue_avu_feature_metatag_ibfk_1`
    FOREIGN KEY (`feature_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_feature` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_feature_segment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_feature_segment` (
  `feature_name` VARCHAR(50) NOT NULL,
  `ref_end` INT(11) NOT NULL,
  `ref_seq_name` VARCHAR(50) NOT NULL,
  `ref_start` INT(11) NOT NULL,
  `splice_index` INT(11) NOT NULL,
  `transcription_index` INT(11) NOT NULL,
  `translation_modifier_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`feature_name`, `ref_end`, `ref_seq_name`, `ref_start`),
  INDEX `ref_seq_name` (`ref_seq_name` ASC, `feature_name` ASC),
  CONSTRAINT `hcv_glue_avu_feature_segment_ibfk_1`
    FOREIGN KEY (`ref_seq_name` , `feature_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_feature_location` (`ref_seq_name` , `feature_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_hospital` (
  `id` VARCHAR(50) NOT NULL,
  `hospital_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_member_floc_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_member_floc_note` (
  `alignment_name` VARCHAR(50) NOT NULL,
  `feature_name` VARCHAR(50) NOT NULL,
  `ref_seq_name` VARCHAR(50) NOT NULL,
  `sequence_id` VARCHAR(50) NOT NULL,
  `source_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`alignment_name`, `feature_name`, `ref_seq_name`, `sequence_id`, `source_name`),
  INDEX `ref_seq_name` (`ref_seq_name` ASC, `feature_name` ASC),
  CONSTRAINT `hcv_glue_avu_member_floc_note_ibfk_1`
    FOREIGN KEY (`ref_seq_name` , `feature_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_feature_location` (`ref_seq_name` , `feature_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_module` (
  `config` LONGBLOB NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_module_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_module_resource` (
  `content` LONGBLOB NULL DEFAULT NULL,
  `module_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`module_name`, `name`),
  CONSTRAINT `hcv_glue_avu_module_resource_ibfk_1`
    FOREIGN KEY (`module_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_module` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_patient` (
  `id` VARCHAR(50) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `diagnosis_date` DATE NULL DEFAULT NULL,
  `country_of_birth` VARCHAR(50) NULL DEFAULT NULL,
  `nationality` VARCHAR(50) NULL DEFAULT NULL,
  `ethnicity` VARCHAR(100) NULL DEFAULT NULL,
  `city_of_residence` VARCHAR(50) NULL DEFAULT NULL,
  `nhs` INT(11) NULL DEFAULT NULL,
  `gender` VARCHAR(50) NULL DEFAULT NULL,
  `hiv_infection` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_project_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_project_setting` (
  `name` VARCHAR(50) NOT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_sample` (
  `id` VARCHAR(50) NOT NULL,
  `sample_date` DATE NULL DEFAULT NULL,
  `reception_date` DATE NULL DEFAULT NULL,
  `initial_genotype` VARCHAR(50) NULL DEFAULT NULL,
  `patient_id` VARCHAR(50) NULL DEFAULT NULL,
  `hospital_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_seq_orig_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_seq_orig_data` (
  `packed_data` LONGBLOB NOT NULL,
  `sequence_id` VARCHAR(50) NOT NULL,
  `source_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`sequence_id`, `source_name`),
  INDEX `source_name` (`source_name` ASC, `sequence_id` ASC),
  CONSTRAINT `hcv_glue_avu_seq_orig_data_ibfk_1`
    FOREIGN KEY (`source_name` , `sequence_id`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_sequence` (`source_name` , `sequence_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_treatment` (
  `id` VARCHAR(50) NOT NULL,
  `regime` VARCHAR(50) NULL DEFAULT NULL,
  `treatment_date` DATE NULL DEFAULT NULL,
  `drug_id` VARCHAR(50) NULL DEFAULT NULL,
  `patient_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_variation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_variation` (
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `feature_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `ref_end` INT(11) NULL DEFAULT NULL,
  `ref_seq_name` VARCHAR(50) NOT NULL,
  `ref_start` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`feature_name`, `name`, `ref_seq_name`),
  INDEX `ref_seq_name` (`ref_seq_name` ASC, `feature_name` ASC),
  CONSTRAINT `hcv_glue_avu_variation_ibfk_1`
    FOREIGN KEY (`ref_seq_name` , `feature_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_feature_location` (`ref_seq_name` , `feature_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_var_almt_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_var_almt_note` (
  `alignment_name` VARCHAR(50) NOT NULL,
  `feature_name` VARCHAR(50) NOT NULL,
  `ref_seq_name` VARCHAR(50) NOT NULL,
  `variation_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`alignment_name`, `feature_name`, `ref_seq_name`, `variation_name`),
  INDEX `ref_seq_name` (`ref_seq_name` ASC, `feature_name` ASC, `variation_name` ASC),
  CONSTRAINT `hcv_glue_avu_var_almt_note_ibfk_1`
    FOREIGN KEY (`alignment_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_alignment` (`name`),
  CONSTRAINT `hcv_glue_avu_var_almt_note_ibfk_2`
    FOREIGN KEY (`ref_seq_name` , `feature_name` , `variation_name`)
    REFERENCES `GLUE_TOOLS`.`hcv_glue_avu_variation` (`ref_seq_name` , `feature_name` , `name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_variation_metatag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_variation_metatag` (
  `feature_name` VARCHAR(50) NOT NULL,
  `metatag_name` VARCHAR(50) NOT NULL,
  `metatag_value` VARCHAR(50) NULL DEFAULT NULL,
  `ref_seq_name` VARCHAR(50) NOT NULL,
  `variation_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`feature_name`, `metatag_name`, `ref_seq_name`, `variation_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_who_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_who_country` (
  `id` VARCHAR(50) NOT NULL,
  `m49_code` INT(11) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `full_name` VARCHAR(100) NULL DEFAULT NULL,
  `is_ldc` BIT(1) NULL DEFAULT NULL,
  `is_lldc` BIT(1) NULL DEFAULT NULL,
  `is_sids` BIT(1) NULL DEFAULT NULL,
  `development_status` VARCHAR(20) NULL DEFAULT NULL,
  `who_region_id` VARCHAR(50) NULL DEFAULT NULL,
  `who_sub_region_id` VARCHAR(50) NULL DEFAULT NULL,
  `who_intermediate_region_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_who_intermediate_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_who_intermediate_region` (
  `id` VARCHAR(50) NOT NULL,
  `m49_code` INT(11) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `who_sub_region_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_who_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_who_region` (
  `id` VARCHAR(50) NOT NULL,
  `m49_code` INT(11) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GLUE_TOOLS`.`hcv_glue_avu_who_sub_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLUE_TOOLS`.`hcv_glue_avu_who_sub_region` (
  `id` VARCHAR(50) NOT NULL,
  `m49_code` INT(11) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `who_region_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
